version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cw-spark-master:
    container_name: cw-spark-master
    build:
      context: .
      dockerfile: build/containers/spark/Dockerfile
    environment:
      - SPARK_MODE=master
      - SPARK_HOST=0.0.0.0
    ports:
      - "8080:8080"
    restart: always

  cw-spark-worker:
    container_name: cw-spark-worker
    build:
      context: .
      dockerfile: build/containers/spark/Dockerfile
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://cw-spark-master:7077
      - SPARK_PUBLIC_DNS=localhost
    ports:
      - "8081:8081"
    restart: always